config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :admins, only: [:index]
  resources :devices, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :devices, only: [:index, :show] do
        post 'record', on: :member
      end
    end
  end

  root 'admins#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  has_many :sensor_data
  has_many :health_status
  validates_uniqueness_of :serial_number

  def status
    health_status.last.try(:name)
  end
end

app/models/health_status.rb
class HealthStatus < ApplicationRecord
  belongs_to :device

  STATUS_LIST = %w(
    needs_service
    needs_new_filter
    gas_leak
  )
end

app/models/sensor_data/air_humidity.rb
class AirHumidity < SensorDatum
  UNIT = 'Percent'.freeze

  def default_unit
    UNIT
  end
end

app/models/sensor_data/carbon_monoxide_lvl.rb
class CarbonMonoxideLvl < SensorDatum
  UNIT = 'PPM'.freeze

  def default_unit
    UNIT
  end
end

app/models/sensor_data/temperature.rb
class Temperature < SensorDatum
  UNIT = 'Celcius'.freeze

  def default_unit
    UNIT
  end
end

app/models/sensor_datum.rb
class SensorDatum < ApplicationRecord
  belongs_to :device
  before_create :add_unit

  CATEGORIES = %w(
    air_humidity
    carbon_monoxide_lvl
    temperature
  ).freeze

  def self.record_data(category: nil, value: nil)
    return false unless CATEGORIES.include? category
    create!(type: category.camelcase, value: value)
  end

  def add_unit
    self.unit = self.default_unit
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @devices = Device.all
  end
end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:record]

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  resource_description do 
     name 'Devices'
  end
  
  api :GET, '/v1/devices', 'Show All Devices'
  description 'Display a list of all existing devices'
  error 500, "Something went wrong"
  example <<-EOS
    [
      {
      id: 1,
      serial_number: "123456789",
      registration_date: "2019",
      firmware_version: "1",
      created_at: "2020-01-25T18:54:12.055Z",
      updated_at: "2020-01-25T18:54:12.055Z"
      },
      {
      id: 2,
      serial_number: "123456790",
      registration_date: "2019",
      firmware_version: "2",
      created_at: "2020-01-25T18:54:12.061Z",
      updated_at: "2020-01-25T18:54:12.061Z"
      }
    ]
  EOS

  def index
    @devices = Device.all
    render json: @devices.to_json
  end

  api :GET, '/v1/devices/:id', "Show Device's Details"
  desc 'Get information of a device given a specific id'
  param :id, String, desc: 'id of the requested user'
  error 404, "No device with that id was found"
  error 500, "Something went wrong"
  example <<-EOS
    {
      id: 1,
      serial_number: "123456789",
      registration_date: "2019",
      firmware_version: "1",
      created_at: "2020-01-25T18:54:12.055Z",
      updated_at: "2020-01-25T18:54:12.055Z"
    }
  EOS
  def show
    @device = Device.find(params[:id])
    render json: @device, include: :sensor_data
  end

  api :POST, '/v1/devices/:id/record', 'Create a Sensor Record'
  desc 'Send a request to save sensor data from a given device id'
  param :id, String, desc: 'The id of the AC unit'
  param :sensor, Hash, desc: 'device object' do 
    param :category, String, desc: 'the category types of the sensor (e.g: air_humidity, carbon_monoxide_lvl, temperature)'
    param :value, String, desc: 'the value of the sensor'
  end
  error 404, "No device with that id was found"
  error 500, "Something went wrong"
  error :unprocessable_entity, "Could not save the entity."
  example <<-EOS
    sensor: {
      category: 'air_humidity',
      value: "1",
    }
  EOS
  def record
    @device = Device.find(params[:id])
    @device.sensor_data.record_data(category: sensor_params[:category], value: sensor_params[:value])
    render json: @device.to_json, include: :sensor_data
  end

  private

  def sensor_params
    params.require(:sensor).permit(:category, :value)
  end

  def record_not_found(error)
    render json: { error: error.message }, status: :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def show
    @device = Device.find(params[:id])
    @sensor_data = @device.sensor_data
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/admins/index.html.erb
<div class="container-fluid">
<%= link_to('API DOCUMENTATION', apipie_apipie_path, class: 'btn btn-info m-4') %>
  <hr>
  <h1 class='py-3'>Devices</h1>
  <p>This is the list of all the smart AC units that are currently registered.</p>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">serial_number</th>
        <th scope="col">registration_date</th>
        <th scope="col">firmware_version</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @devices.each_with_index do |device, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= device.serial_number %></td>
          <td><%= device.registration_date %></td>
          <td><%= device.firmware_version %></td>
          <td>
            <%= link_to('View', device_path(device.id), class: 'btn btn-light')%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/devices/_sensor_data.html.erb
<h2>Sensor Data Collected</h2>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Type</th>
      <th scope="col">Value</th>
      <th scope="col">Unit</th>
    </tr>
  </thead>
  <tbody>
    <% @sensor_data.each do |data| %>
      <tr>
        <td><%= data.created_at %></td>
        <td><%= data.type.underscore.humanize.gsub('lvl', 'Level') %></td>
        <td><%= data.value %></td>
        <td><%= data.unit %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/devices/show.html.erb
<div class='container-fluid'>
  <%= link_to('Go Back', admins_path, class: 'btn btn-light m-4') %>
  <hr>
  <br>
  <h1>Device # <%= @device.serial_number %></h1>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row">Serial Number</th>
        <td><%= @device.serial_number %></td>
       
      </tr>
      <tr>
        <th scope="row">Registration Date</th>
        <td><%= @device.registration_date %></td>
      <tr>
      <tr>
        <th scope="row">Firmware Version</th>
        <td><%= @device.firmware_version %></td>
      </tr>
    </tbody>
  </table>
  <hr>
  <%= render 'sensor_data' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartAc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- As a heading -->
    <nav class="navbar navbar-light bg-light">
      <span class="navbar-brand mb-0 h1">Smart AC Admin</span>
    </nav>
    <%= yield %>
  </body>
</html>